Algoritmo "estrutura_repeticao"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Marcio
// Descrição   : Executar dez vezes a mesma linha de comando
// Autor(a)    : Samuel Balduino de Almeida
// Data atual  : 17/03/2022
Var
// Seção de Declarações das variáveis
i : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 10 ate 1  passo -1  faca
     escreval(i)
fimpara
 


Fimalgoritmo